### ISSUE TITLE
[Feature] Prevent Image Drag

### ISSUE THREAD

**Issue by kholy87** [img-mapper/react-img-mapper#15]
**Is your feature request related to a problem? Please describe.**
When I am trying to use the feature for onMouseDown it also allows me to drag the image behind the mapping. So if the user moves the mouse a little while holding the button it causing the image to go into dragging mode

**Describe the solution you'd like**
I'd like to prevent the image from being dragged at all, or have an option to enable this

**Additional context**
If you need to see an example of this happening I can DM you. Due to what I am working on I cannot share publicly

**Comment by NishargShah** [comment]
Hello @kholy87, sorry for the late reply, I forgot about this issue, I just checked and worked on it but I didn't found any issue like this, can you please share any video of that so I can reproduce it and solve it.

**Comment by kholy87** [comment]
So if i were to click one of the buttons and hold my mouse button down and drag to the right this is the effect I get. https://imgur.com/Db5UfSk I trimmed off a lot of the image but if you need to reach me my email should be on my commit. I just can't share the full image public

**Comment by NishargShah** [comment]
Hello @kholy87, can you please share the video on nishargshah3101@gmail.com because your image is not clear

**Comment by NishargShah** [comment]
Hello @kholy87, I am waiting for your reply :)

**Comment by NishargShah** [comment]
I am closing this issue because of the inactivity of the author
