### ISSUE TITLE
onClick prop callback not working

### ISSUE THREAD

**Issue by saxenanurag** [img-mapper/react-img-mapper#17]
**Describe the bug**
When the onClick property is called on the mapper, nothing happens. 

**To Reproduce**
1. In the react-docs example, add onClick callback to `clearButtonTemplate` like so: 
```js
  const clicked = (area,i,e) => {
    console.log(area,i,e);
  }

  return (
    <Fragment>
      <ImageMapper
          containerRef={myRef}
          src={URL}
          map={MAP}
          stayMultiHighlighted
          onClick={(area,i,e)=>this.clicked(area,i,e)}
       />
       <button onClick={handleClear}>Clear</button>
    </Fragment>
  )
}
```

**Error Stack**
None

**Expected behavior**
console should log `area`, `i`, and `e`

**Comment by NishargShah** [comment]
Please check again, it's working fine 

Link: https://codesandbox.io/s/react-img-mapper-example-8pv4g

**Comment by saxenanurag** [comment]
Thank you.
