### ISSUE TITLE
Type map is incompatible.

### ISSUE THREAD

**Issue by Ferboox** [img-mapper/react-img-mapper#18]
**Describe the bug**
Error on parameter map on the ImageMapper component.

**To Reproduce**
Use the component <ImageMapper src{URL} map={MAP}

**Error Stack**
Type '{ name: string; areas: { id: string; title: string; shape: string; name: string; fillColor: string; strokeColor: string; coords: number[]; polygon: number[][]; }[]; }' is not assignable to type 'Map'.

**Expected behavior**
Draw the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/46915322/127894139-818f7521-efc8-4caa-9ca2-c3ff28857a91.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [Chrome]
 - Version: [92.x]

**Additional context**
I'm using this on my app build with React and Ionic 5.

**Comment by NishargShah** [comment]
Can you please provide the `MAP` json?

**Comment by Ferboox** [comment]
I'm using the JSON that are on the npm page: https://raw.githubusercontent.com/img-mapper/react-docs/master/src/assets/example.json

**Comment by NishargShah** [comment]
Got the issue, it's because of PR I merged into the package

PR: https://github.com/img-mapper/react-img-mapper/pull/16/files#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR28

Please check the new package version `V1.2.1`

https://www.npmjs.com/package/react-img-mapper

**Comment by Ferboox** [comment]
¡Thanks, mate!
