### ISSUE TITLE
Display an array of Area ID's

### ISSUE THREAD

**Issue by hainsdominic** [img-mapper/react-img-mapper#19]
**Is your feature request related to a problem? Please describe.**
I am trying to display an array of Area ID's on a map.

Is it possible? I read the documentation and I have no clue on how to do it. 

Thank you!

**Comment by hainsdominic** [comment]
I tried adding the "preFillColor" property to the map JSON, but I get an errror: TypeError: Cannot read property 'naturalWidth' of null

**Comment by NishargShah** [comment]
Can you show some demo here like in code sandbox, so I know where you go wrong

**Comment by NishargShah** [comment]
I am closing this issue because of the inactivity of the author, feel free to reopen it with a demo
