### ISSUE TITLE
Disabling individual area coords.

### ISSUE THREAD

**Issue by meljason** [img-mapper/react-img-mapper#2]
**Is your feature request related to a problem? Please describe.**
It is not a big problem but I think a bool disabled function would be great as sometimes on site-plans, I want to disable certain sold-out area.

**Describe the solution you'd like**
Probably something like disable boolean that we can add when we declare the map const.

**Describe alternatives you've considered**
Currently I am updating the id to empty so that users cannot click on that certain area. But this is not the best solution because users can technically still click on it. It is just that it is not linked to that id because I removed it. A disable boolean would be a better way to do it.

**Comment by NishargShah** [comment]
Great Feature, I am willing to add that feature to my project

**Comment by meljason** [comment]
Awesome! Thank you very much. Great work!

**Comment by NishargShah** [comment]
I am planning to add `active: true | false` in JSON.

If you are passing `active: false` in a specific area it will not highlight that specific area.

it will give similar results to that https://img-mapper.github.io/react-docs/?path=/story/examples-area--show-highlighted-area

**Comment by meljason** [comment]
That's perfect!

**Comment by NishargShah** [comment]
Hello @meljason 

Please upgrade your version to `v1.0.3`

Here is the docs https://img-mapper.github.io/react-docs/?path=/story/examples-area--in-array-show-highlighted-area

Thanks

**Comment by meljason** [comment]
Hey @NishargShah I did

```
{
      "coords" : [ 416, 296, 437, 245, 454, 247, 501, 246, 427, 308 ],
      "id" : "22",
      "name" : "22",
      "preFillColor" : "rgba(255, 255, 255, 0.70)",
      "shape" : "poly"
      "active": "false"
    },
``` 
But it seems like it is still highlighting, am I doing something wrong?

**Comment by NishargShah** [comment]
did you upgrade the package to `v1.0.4`?

**Comment by meljason** [comment]
@NishargShah Yes it works now. I just forgot to restart my localhost. Thank you!
