### ISSUE TITLE
The new area active (true/false) function still allows users to click and access the data from it.

### ISSUE THREAD

**Issue by meljason** [img-mapper/react-img-mapper#3]
**Is your feature request related to a problem? Please describe.**
Yes. In the new version, the users are now able to disable highlighting in certain area of the map. However, they can still click on it which allow them to access the data.

**Describe the solution you'd like**
I would like to be able to completely disable that area when active is false.

**Describe alternatives you've considered**
Alternative would be updating name attribute to empty so that they cannot access the data from it.

**Comment by NishargShah** [comment]
Got it but `active` property is still a good feature, I will keep it and announce the new keyword `disable` for that

Thanks

**Comment by NishargShah** [comment]
Hello @meljason 

Please upgrade your version to `v1.1.0`

Here are the docs https://img-mapper.github.io/react-docs/?path=/story/examples-area--in-array-disabled-area

Thanks
