### ISSUE TITLE
Smooth Borders/Highlights

### ISSUE THREAD

**Issue by ghost** [img-mapper/react-img-mapper#31]
**Is your feature request related to a problem? Please describe.**
When the image map is pinched in on mobile, the borders/highlighted regions are pixelated/blurry.

**Describe the solution you'd like**
Borders/Highlighted regions should be smooth when zoomed in.

**Describe alternatives you've considered**
Considering the alternative of going without borders; 

**Additional context**
On Chrome/Devtools, enable the mobile viewport/debugger, inspect the image map, and replace the image used with an SVG.
Use Shift-Click on the mobile viewport in devtools tools to drag and simulate pinch to zoom as it would occur on a mobile device. 
Notice that while the SVG remains sharp, the border drawn by `react-img-mapper` is blurry and pixelated.

![image](https://user-images.githubusercontent.com/84352648/156045280-03d0c2df-7d24-4c91-8b98-16a4918a3d35.png)

**Comment by NishargShah** [comment]
Ok, I will check that :)

**Comment by NishargShah** [comment]
@bzsTNguyen Can you please provide the example of your problem

**Comment by NishargShah** [comment]
@bzsTNguyen I can not reproduce this problem, please provide an example in codesandbox

**Comment by NishargShah** [comment]
I am closing this issue because of the inactivity of the author, feel free to reopen it with a demo
