### ISSUE TITLE
When updating the highlight colors dynamatically onClick of a button, all the areas turn to the color of the highlight.

### ISSUE THREAD

**Issue by meljason** [img-mapper/react-img-mapper#4]
**Describe the bug**
When updating the highlight colors dynamatically onClick of a button, all the areas turn to the color of the highlight. I have to hover over it for the color to update.

**To Reproduce**
I have populated my firebase realtime database with the data of map coordinates with the other attributes like so.

```
const [mapCoords, setMapCoords] = useState({
	'name': 'my-map',
});
``` 
Then used useEffect to populate it
``` 
useEffect(() => {
		async function getData() {
			await firebase
				.database()
				.ref('...')
				.once('value', (snapshot) => {
					var mapCoordObj;
					var areaArr = [];
					snapshot.forEach((lot) => {
						var mapCoordVal = lot.val().mapCoords;

						areaArr.push(mapCoordVal);

						var mapCoordChild = lot.child('mapCoords');

						console.log('mapCoordChild: ' + JSON.stringify(mapCoordChild));

						mapCoordChild.forEach((child) => {
							console.log('childdddd: ' + JSON.stringify(child));
						});

						console.log('mapCoordVal ' + JSON.stringify(mapCoordVal));

						mapCoordObj = {
							...mapCoords,
							areas: areaArr,
						};
					});

					console.log('areaa: ' + areaArr);

					setMapCoords(mapCoordObj);
				});
		}
		getData();
	}, []);
```

Then I have a button
```
<button onClick={handleChangeColor}>Change Color</button>

const handleChangeColor = () => {
          firebase
			.database()
			.ref('...')
			.orderByChild('available')
			.equalTo('pending')
			.on('value', (snapshot) => {
				snapshot.forEach((lot) => {
					var child = firebase
						.database()
						.ref('...')
						.child(lot.key)
						.child('mapCoords');

					child.update({
						preFillColor: 'rgba(255, 255, 168, 0.70)',
						name: id,
						active: true,
					});
				});
			});
}
```

This would handle the color change. However, when I click on the button, it will turn all areas to the color of the highlight like so:

![image](https://user-images.githubusercontent.com/34180725/112764947-cbcf4b00-8fd8-11eb-9a16-c19eb388a6c7.png)

To change the color, I would have to hover over any of those areas and it will change it.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: Version 89.0.4389.82 (Official Build) (64-bit)

**Comment by NishargShah** [comment]
Can you provide me any of the video that describes the bug clearly?

**Comment by NishargShah** [comment]
Can you provide me any of the video that describes the bug clearly?

**Comment by meljason** [comment]
@NishargShah Yes please find the video in this following link:

https://vimeo.com/530276731

**Comment by NishargShah** [comment]
Thanks for letting me know this issue and I think its very good catch and serious issue, let me check it

**Comment by NishargShah** [comment]
Thanks for letting me know about this issue and I think its a very good catch and serious issue, let me check it

**Comment by NishargShah** [comment]
Yes, I found one issue, if you defined `preFillColor` and click on the button, `preFillColor` is ignored and you must hover it to add `preFillColor` in the area but I think your issue is not similar to a founded issue.

> all the areas turn to the color of the highlight. I have to hover over it for the color to update.

I checked from my side but I didn't find anything. please check if you added the same `id` or `preFillColor` to all of them

**Comment by NishargShah** [comment]
Hello @meljason

> Yes, I found one issue, if you defined `preFillColor` and click on the button, `preFillColor` is ignored and you must hover it to add `preFillColor` in the area but I think your issue is not similar to a founded issue.

I solved the above issue, please upgrade your version to `v1.1.2`.

I am not confirmed that your issue is still solved or not so I am keeping this issue open.

Thanks.

**Comment by meljason** [comment]
I would like to confirm that the fix has been solved in the new version that you rolled out. Thank you!
