### ISSUE TITLE
Canvas height is 0. Fails to set the right canvas height

### ISSUE THREAD

**Issue by DVGY** [img-mapper/react-img-mapper#43]
Sometimes canvas height is 0. There is a bug, I have seen that sometimes `react-img-mapper` fails to set right canvas height. I am using `react-image-mapper` as of now and it works fine, it always sets the height of the canvas right 

I have created a code sandbox here is the [link](https://codesandbox.io/s/nervous-easley-1y9e23?file=/src/App.js). If you open the the rendering image in new tab. It fails to load the canvas height

**Desktop (please complete the following information):**
 Windows
 Chrome

**Comment by pavelvzhilin** [comment]
Same thing happens to me. On a first render and following page refresh canvas element and its parent div can randomly get a 0px height and 0px width and thus become hidden. In my case it seems quite random and doesn't correlate with a number of a render. Recorded a video with a demonstration. 

I think it correlates with #42 

https://user-images.githubusercontent.com/69286319/169506212-6a37585b-e8c6-418b-b99d-1027f6291c3d.mp4


Doubt, but probably with a #20 either.

**Comment by NishargShah** [comment]
Hey, @DVGY I am working on this issue and @pavelvzhilin Thanks for providing the video that actually shows a problem.

**Comment by NishargShah** [comment]
Hello @DVGY and @pavelvzhilin, please check version **1.3.0** and let me know, you are facing these problems on that version?

**Comment by DVGY** [comment]
@NishargShah working fine in 1.3.0

**Comment by pavelvzhilin** [comment]
@NishargShah yep, me either - it is all good in 1.3.0. Thank you for the advice.

**Comment by NishargShah** [comment]
Hello @DVGY @pavelvzhilin Resolved in [V1.5.0](https://www.npmjs.com/package/react-img-mapper/v/1.5.0)

Please check and free feel to reopen if you found any bugs related to this issue.
