### ISSUE TITLE
react-img-mapper with zoom and pan? 

### ISSUE THREAD

**Issue by DVGY** [img-mapper/react-img-mapper#44]
Is there any **example**, react-img-mapper **with zoom and pan** library? 
I want my canvas to be zoomed and panned (react zoom pan pinch library) properly, is there any example available? Thre
Thanks

**Comment by NishargShah** [comment]
https://img-mapper.github.io/react-docs/?path=/story/examples-area--zoom-in-zoom-out-area

This is what you want, isn't it?

**Comment by DVGY** [comment]
> 

This is not the type of zoom I want. The zoom should be based on mouse pointer. Anyways, this kind of zoom and pan exist in react zoom pan pinch lib. I was looking if there is way to integrate them,  or with any other lib

**Comment by NishargShah** [comment]
The purpose of this project is different.

For future visitors, please check out https://www.npmjs.com/package/react-zoom-pan-pinch, it is a good library for this type of zooming.
