### ISSUE TITLE
Sometimes the highlight on hover does not highlight in the right area on the image.

### ISSUE THREAD

**Issue by meljason** [img-mapper/react-img-mapper#45]
**Describe the bug**
This is an intermittent bug. Sometimes when the page loads, highlight on hover does not highlight in the right area (please see image provided). It happens when I use the attribute of `responsive={true}` in my `<ImageMapper />` tag. 

**To Reproduce**
This is how I wrote my ImageMapper for responsiveness

```
//this is before the render function
const [imageMapperWidth, setImageMapperWidth] = useState(0);
const imageMapperRef = useRef();

useEffect(() => {
	setImageMapperWidth(imageMapperRef.current.offsetWidth);
}, []);

let movement_timer = null;

window.addEventListener('resize', () => {
	clearTimeout(movement_timer);
	movement_timer = setTimeout(() => {
		if (imageMapperRef.current?.offsetWidth) {
			setImageMapperWidth(imageMapperRef.current.offsetWidth);
		}
	}, 1000);
});

//this is in my render
<ImageMapper
	src={url}
	map={
		...
	}
	responsive={true}
	parentWidth={imageMapperWidth}
	fillColor={'rgba(71, 131, 230, 0.70)'}
	strokeColor={'rgba(71, 131, 230)'}
	onClick={(area) => {
		handleClickLot(area);
	}}
	onMouseEnter={(area) => {
		enterArea(area);
		handleMouseMove(area);
	}}
	onMouseLeave={(event) => {
		handleMouseLeave(event);
	}}
/>
```

**Expected behavior**
When the component loads, all the highlights should be in the proper designated area. This also applies when resizing the screen.

**Screenshots**
Video of issue:
https://share.vidyard.com/watch/PFVv2Td5TRLN7YPLGDPkhQ?

Screenshot of issue 
![image](https://user-images.githubusercontent.com/34180725/173349691-4c033269-7d49-43e6-884e-11501848cc51.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by NishargShah** [comment]
Can you please come up with a good example such as in Codesandbox?

**Comment by NishargShah** [comment]
Due to no example from the @meljason, I am closing it.

As per my understanding from your example, I create one example: https://codesandbox.io/s/jovial-wave-v6gt7e?file=/src/App.js
