### ISSUE TITLE
Keyword active (false) seems to deactivate the preFillColor option.

### ISSUE THREAD

**Issue by meljason** [img-mapper/react-img-mapper#5]
**Describe the bug**
When declaring the map coordinates, if you put active = false, it deactivates the preFillColor option. 

**To Reproduce**
` ` `
const map = {
        active = false,
        preFillColor = "rgba(69, 82, 94, 0.70)",
        id = 1,
        name = "1",
        shape = "poly",
        coords = [...]
}
` ` `

**Expected behavior**
The active = false should not disable the preFillColor.

**Desktop (please complete the following information):**
 - Browser: [Chrome]
 - Version: [89.0.4389.90 ]

**Comment by NishargShah** [comment]
Hello @meljason, nice catch

Please upgrade your version to v1.1.1

Thanks

**Comment by meljason** [comment]
Awesome. Works perfectly. Thank you!
