### ISSUE TITLE
Make a map with two polygons to behave as one area

### ISSUE THREAD

**Issue by Mostafa-YMS** [img-mapper/react-img-mapper#52]
**Is your feature request related to a problem? Please describe.**
Is it possible to make a map with two polygons to behave as one area

**Describe the solution you'd like**
The ability to provide an area with array of polygon or connect two or more areas together when they have the same title.

**Comment by NishargShah** [comment]
Two polygons in one area are not supported yet.

If you find any solution to it, could you let me know?

Thanks :)
