### ISSUE TITLE
Unhighlighting on click is delayed until mouse exits current area

### ISSUE THREAD

**Issue by andersweinstein** [img-mapper/react-img-mapper#53]
**Describe the bug**
In the demo, in cases when a mouse click should cause unhighlighting of a previously highlighted area, the unhighlighting does not render immediately. Rather, it appears to be delayed until the mouse exits the area it is currently over.

**To Reproduce**
In the demo for "Toggle Stay Highlighted Area": click one area, say the ceiling. The ceiling is highlighted. Now click the ceiling again to toggle its highlighting off. The ceiling remains highlighted. Move the mouse out of the ceiling, say, onto the wall. NOW the ceiling shows as unhighlighted.

In the demo for "Stay Selected Highlighted Area": click one area, say the celing The ceiling is highlighted. Then click another area, say the window. The window is highlighted, but the ceiling is NOT unhighlighted. Move the mouse out of the window, say onto the surrounding wall. NOW the ceiling shows as unighlighted.

**Expected behavior**
Expected the unhighlighting of the previously highlighted area to be visible immediately after the click to give immediate feedback on the effect of the mouse click on the selection state. 

**Desktop**
 - OS: MacOS Monterey 12.5.1
 - Browser: Chrome
 - Version: 105.0.5195.125 (Official Build) (x86_64)

**Comment by hirpararajesh99** [comment]
i ' m also facing same issue. @andersweinstein do you have any solution

**Comment by andersweinstein** [comment]
@hirpararajesh99 Sorry, I have nothing to offer. I rejected this component because of this bug and non-responsiveness by the component author.

**Comment by NishargShah** [comment]
Hello @andersweinstein @hirpararajesh99 Resolved in [V1.4.3](https://www.npmjs.com/package/react-img-mapper/v/1.4.3)

Please check and free feel to reopen if you found any bugs related to this issue.
