### ISSUE TITLE
Is there a way to have pointer over highlited area?

### ISSUE THREAD

**Issue by gmunumel** [img-mapper/react-img-mapper#57]
Hello, 

Thanks for the library. 

I want to know if it's possible to have pointer cursor over highlighted area? I'd like to have as CSS, like this:

```typescript
<ImageMapper
      src={url}
      map={map}
      width={180}
      height={561}
      style={{ cursor: 'pointer' }}
    />
```

**Comment by NishargShah** [comment]
Hello @gmunumel 

You can apply `cursor` css on `img-mapper-map`, it will apply to the whole image, not to highlighted canvas.

Demo: https://codesandbox.io/s/trusting-wright-htxxbg?file=/src/App.js

**Comment by NishargShah** [comment]
Feel free to reopen, if you have any doubts.

**Comment by bmakan** [comment]
This didn't work for me. What worked was adding styles for `map` element.

```css
.container map {
    cursor: 'pointer';
}
```

Now when I hover over mapped areas my cursor changes.
