### ISSUE TITLE
[Feature] Adding labelling to areas of the image.

### ISSUE THREAD

**Issue by meljason** [img-mapper/react-img-mapper#7]
**Is your feature request related to a problem? Please describe.**
It is not a problem related feature. But it would be great to have a feature that allows you to add customized labelling to each areas. 

**Describe the solution you'd like**
I was thinking something like the preFillColor, but instead it is called something like "label" which would show a customized text on that coordinated area. So in
` ` `
const map = [id: "1", name: "1", coords: [...], label: "example"]
` ` `

**Comment by NishargShah** [comment]
Good Feature, I will think about it and add it soon

**Comment by NishargShah** [comment]
I thought a lot about that and I feel that is not a required feature because label word can be more or less and maintaining the style that is unnecessary, but you can use `onMouseMove` function callback to complete your goal

Thanks

**Comment by meljason** [comment]
@NishargShah Thanks for the recommendation. But could you please elaborate more on that? How would I display a certain text on specifics coordinates on the image with `onMouseMove` ?

**Comment by NishargShah** [comment]
In example,

`onMouseMove` you got an area object of the hovered area so, If you want to show the label only on the `window` area then update the state and check if the area is `windows` then show the text.

**Comment by meljason** [comment]
@NishargShah Hey, I followed your suggestion, however, that would show the text for one area when I hover over that area. Do you think if there might be a way to loop over each area to display all the texts over all areas?

**Comment by NishargShah** [comment]
Demo: https://coldiary.github.io/react-image-mapper/

**Comment by salmanedhi** [comment]
> Demo: https://coldiary.github.io/react-image-mapper/

Hi @NishargShah , the message logic was not displayed in this example. Could you please share the message logic as well? Especially the part where I can get the current coordinates where my mouse is pointing to?

**Comment by NishargShah** [comment]
Example of getting the currently specified area coordinates: https://codesandbox.io/s/get-coordinates-on-mouse-move-h2gh4?file=/src/App.js

**Comment by miladezzat** [comment]
We need to make label appear by default @NishargShah

**Comment by NishargShah** [comment]
Good feature, I will try to add it in next versions, for now please check below link

Codesandbox: https://codesandbox.io/s/get-coordinates-title-by-default-dkiind

**Comment by miladezzat** [comment]
> Good feature, I will try to add it in next versions, for now please check below link
> 
> Codesandbox: https://codesandbox.io/s/get-coordinates-title-by-default-dkiind

I did the same way, it will be good if you added it on the package 😄 , and if you can added Zoom on the image 😸

**Comment by Manubi** [comment]
any news on this one? :D

**Comment by Manubi** [comment]
if anyone needs something similar I post my version of it... 
```typescript
import { useEffect, useState } from "react";
import { toast } from "react-hot-toast";
import ImageMapper from "react-img-mapper";
import areas from "./groupphoto.json";

export type TPerson = {
  coords: number[];
  id: string;
  name: string;
  shape: string;
};

const getCenterCoords = (areas: TPerson[], scaleHeight: number) =>
  areas.map((area) => {
    if (area.shape === "circle") {
      const [x, y, r] = area.coords;
      const yOffset = r + 20 * scaleHeight;
      return {
        ...area,
        center: {
          x: x,
          y: y + yOffset,
        },
      };
    }
    return area; // Return original area for non-circle shapes
  });

export function GroupPhoto() {
  const URL = "https://re-solute.eu/assets/conference/team.jpg";
  const imgWidth = 6732; // Original image width
  const imgHeight = 4488; // Original image height
  const aspectRatio = imgHeight / imgWidth;
  const [extendedAreas, setExtendedAreas] = useState<any[]>([]);
  const [hoveredArea, setHoveredArea] = useState<any>(null);

  const [adjustedAreas, setAdjustedAreas] = useState<any>([]);
  const [dimensions, setDimensions] = useState({
    width: window.innerWidth,
    height: window.innerWidth * aspectRatio,
  });

  useEffect(() => {
    const scaleWidth = dimensions.width / imgWidth;
    const scaleHeight = dimensions.height / imgHeight;

    // Adjust the coordinates of the areas based on the new dimensions
    const newAreas = areas.map((area) => {
      if (area.shape === "circle") {
        return {
          ...area,
          coords: [
            area.coords[0] * scaleWidth,
            area.coords[1] * scaleHeight,
            area.coords[2] * scaleWidth,
          ],
        };
      }
      // Add conditions for other shapes (e.g., rectangle, polygon) if needed
      return area;
    });

    setAdjustedAreas(newAreas);
    setExtendedAreas(getCenterCoords(newAreas, scaleHeight));
  }, [dimensions]);

  const MAP = {
    name: "re-solute",
    areas: adjustedAreas,
  };

  useEffect(() => {
    const handleResize = () => {
      setDimensions({
        width: window.innerWidth,
        height: window.innerWidth * aspectRatio,
      });
    };

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  const handleCopyClick = async (textToCopy: string) => {
    try {
      await navigator.clipboard.writeText(textToCopy);
      toast.success(`Copied "${textToCopy}" to clipboard!`);
    } catch (err) {
      toast.error("Failed to copy name to clipboard.");
    }
  };

  return (
    <div className="w-full h-full relative lg:mb-12 mt-6">
      <ImageMapper
        src={URL}
        map={MAP}
        height={dimensions.height}
        width={dimensions.width}
        onMouseEnter={(area) => {
          setHoveredArea(area);
        }}
        onMouseLeave={() => {
          setHoveredArea(null);
        }}
        strokeColor="rgba(0, 0, 0, 0)"
        onClick={(area) => {
          handleCopyClick((area as any).name);
        }}
      />

      {hoveredArea &&
        extendedAreas.map(
          (area) =>
            area.name === hoveredArea.name && (
              <span
                key={area.id}
                className="text-primary bg-white opacity-90 px-2 py-1 text-sm  rounded-md font-semibold"
                style={{
                  position: "absolute",
                  top: `${area.center.y}px`,
                  left: `${area.center.x}px`,
                  transform: "translate(-50%, 0%)", // Center it horizontally
                  zIndex: 1001,
                }}
              >
                {area.name}
              </span>
            )
        )}
    </div>
  );
}
```
