### ISSUE TITLE
using Tailwind in the react project 

### ISSUE THREAD

**Issue by marcuspx** [img-mapper/react-img-mapper#74]
**Describe the bug**
I use a React project without Tailwind the image and hover work well
but I installed "tailwindcss": "3.3.3", after that the image does not show up, the canva and map does not work as expected nothing happens

only when I comment this line it works again
/* @tailwind base; */

**Comment by NishargShah** [comment]
Please check: https://github.com/img-mapper/react-img-mapper/issues/67
