### ISSUE TITLE
Size Height Width

### ISSUE THREAD

**Issue by marcuspx** [img-mapper/react-img-mapper#75]
**Describe the bug**
I set up a Different Height and Width the image size is working but the canvas or map is not adapting to the new values the hover breaks is not responsive
https://codesandbox.io/p/sandbox/zen-waterfall-dygwpg?file=%2Fapp%2Fpage.tsx%3A617%2C63

**Comment by NishargShah** [comment]
You don't need to set height and width both to get responsiveness canvas, just set parentWidth and you are good to go.

please read https://img-mapper.github.io/react-docs/?path=/story/examples-responsive-map--responsive-dimensions
