### ISSUE TITLE
Encountered Two Children with the Same Key, index cannot be used for areaKeyName without using ts-ignore

### ISSUE THREAD

**Issue by melihcoban** [img-mapper/react-img-mapper#76]
**Describe the bug**
Having same id in the MapAreas[] list throws an exception with ```Encountered two children with the same key```.

**To Reproduce**
1. Define map areas with id's
Example object:
```
{
          id: x.baseId,
          shape: 'rect',
          coords: [0, 185, 237, 240],
          preFillColor: 'rgb(255,255,255,0)',
}
```
3. Use ImageMapper component
```
<ImageMapper
          src={area.imgSrc}
          onClick={event => openModalForStructureDetail(event)}
          map={{name: area.id, areas: area.componentMap as MapAreas[]}}
          onLoad={e => handleLoadedImage(e)}
        />
```
**Error Stack**
```
Warning: Encountered two children with the same key, `13`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at map
    at div
    at ImageMapper (http://localhost:5173/node_modules/.vite/deps/react-img-mapper.js?v=2ed9ea2e:398:32)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-2NS6L6TO.js?v=2ed9ea2e:4971:18
    at http://localhost:5173/node_modules/.vite/deps/chunk-2NS6L6TO.js?v=2ed9ea2e:16193:14
    at http://localhost:5173/node_modules/.vite/deps/chunk-2NS6L6TO.js?v=2ed9ea2e:16331:14
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-2NS6L6TO.js?v=2ed9ea2e:4971:18
    at http://localhost:5173/node_modules/.vite/deps/chunk-2NS6L6TO.js?v=2ed9ea2e:20772:14
    at div
```

**Expected behavior**
Adding ```areaKeyName="index"``` solves the issue, however declaration in the ```types.d.ts``` defines that ```areaKeyName``` only accepts id ``` areaKeyName?: 'id';```. I need to add ignore ```//@ts-ignore``` for it to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [Electron (chromium-based)]
 - Version: [25.4]

**Additional context**
I can't apply the fix stated in this [issue](https://github.com/img-mapper/react-img-mapper/issues/1) because I cannot edit ```areaKeyName``` without getting compiler errors.

**Comment by NishargShah** [comment]
Id is unique in the JSON, do you have the same id in another JSON object?

**Comment by NishargShah** [comment]
Hello @melihcoban, this issue is resolved in the newer pre-release

Please check https://www.npmjs.com/package/react-img-mapper/v/2.0.0-alpha.1

Thanks :)
