### ISSUE TITLE
Disable areas hover

### ISSUE THREAD

**Issue by maple146** [img-mapper/react-img-mapper#77]
**Is your feature request related to a problem? Please describe.**
Hello! I'm creating a game to find the differences between two images with this library.
The problem is that when I hover the mouse over an area, the hover style spoils the answer.

**Describe the solution you'd like**
I would like to know if there's any way to hide or delete the hover styles of the map areas and also keep the styles of the shapes after clicking on them.

**Describe alternatives you've considered**
I've tried using the .img-mapper-map class and targeting the area but it didn't work.

My guess was that doing something like this would disable the styles, but the only property that worked was the pointer one:
```
.img-mapper-map {
  area:hover {
    cursor: pointer;
    fill: rgba(255, 255, 255, 0.0);
    border-color: rgba(255, 255, 255, 0.0);
    border: none;
    border-style: none;
    background: rgba(255, 255, 255, 0.0);
    background-color: rgba(255, 255, 255, 0.0);
  }
}
```

**Additional context**
![game](https://github.com/img-mapper/react-img-mapper/assets/65734376/5ec9f5fa-a6ad-4b2e-8c1d-681a0e14045e)

**Comment by NishargShah** [comment]
Hello @maple146, I didn't get the actual problem, can you please explain this in detail and please check the `active` prop if it resolve your issue

**Comment by maple146** [comment]
Hi @NishargShah!
Sorry for the lack of clarity in the question.
What I wanted was to disable this hover effect when I'm hovering over an area:
![hover effect](https://github.com/img-mapper/react-img-mapper/assets/65734376/e7031490-e253-4927-b399-e206b14e8feb)

I couldn't disable the hover effect without disabling the active area style, so I ended up implementing it another way.
Thank you for your time!
