### ISSUE TITLE
onClick works one time

### ISSUE THREAD

**Issue by geeflaxx** [img-mapper/react-img-mapper#80]
**Describe the bug** A clear and concise description of what the bug is.
I want to use a function if I am clicking on an area. 
The first time the function will be used. After clicking on the other area, nothing happend.

At the screenshot you can see: Postit, keyboard and desktop is marked. 

in the console only one time shows the log message "Logging a message!'", It should be everytime if I am click on the different area. Do you have a solution?

**To Reproduce** Steps to reproduce the behavior:

1. Go to the page, hover on all the polygons
2. Click on a polygon
3. Console output shows right
4. After clicking on another polyigon the output don't show up

![grafik](https://github.com/img-mapper/react-img-mapper/assets/21129138/165c5da2-93af-4bc4-b275-eff4524b77bb)

**Desktop (please complete the following information):**

- OS: Linux, arch
- Browser: firefox
- Version: latest

**Additional context** Add any other context about the problem here.
I use for usually typescript. 

```
const logMessage = () => {
    console.log('Logging a message!');
};
```

`<ImageMapper src={URL} map={MAP} stayMultiHighlighted={true} onClick={logMessage}/>`

**Comment by NishargShah** [comment]
Hello @geeflaxx, can you please provide the example in code sandbox? and if possible, please use the latest version https://www.npmjs.com/package/react-img-mapper/v/2.0.0-alpha.3

**Comment by NishargShah** [comment]
Due to no example from the @geeflaxx, I am closing it.
