### ISSUE TITLE
 area based is toggle check and update  is possible?

### ISSUE THREAD

**Issue by muhammetbilgin** [img-mapper/react-img-mapper#81]
I will work on a part of computer image and using toggle feature. When user click on a part, open a modal and user choose a option for that part. Its working as well but components on image too close each others. I want to user can confirm selection. If user miss click on object, user can say oh its miss click take toggle back.

is toggle update possible?

![image](https://github.com/img-mapper/react-img-mapper/assets/72626321/0263ea0d-c872-4174-b0aa-120bfe2a7e6f)

**Comment by NishargShah** [comment]
Hello @muhammetbilgin, It is possible in the new release, please checkout. https://www.npmjs.com/package/react-img-mapper/v/2.0.0-alpha.3

**Comment by muhammetbilgin** [comment]
Hi @NishargShah, i just take a look but i don't understand how its possible. I tried update area's active value but its not effect. Sorry, can u explain it ?

**Comment by NishargShah** [comment]
Hello @muhammetbilgin, Can you please provide me the codesandbox of it, so I can reformat it?

**Comment by NishargShah** [comment]
Due to no example from the @muhammetbilgin, I am closing it.

**Comment by muhammetbilgin** [comment]
Hi, sorry i missed ur notification. 

Usin state for store maps. User select a area then user can cancel it. I want to clear that highlighted rect but i don't know how i can.

I check state, selection doesn't effect usestate. (Mean fillcolor or prefillcolor)


``` js  
const handleCancel = () => {
    setIsModalOpen(false)
    const i = map?.areas.find((item) => item.id === selectedArea?.id)
    console.log(i)
    if (i) {
      //i not have any highligth effect
    }
  }
