### ISSUE TITLE
NPM Version Control

### ISSUE THREAD

**Issue by DnAWebDev** [img-mapper/react-img-mapper#85]
Hi,

I’m using react-image-mapper in a project with React 18 and noticed that the npm versions only support up to React 14. I had to install from GitHub to get the 2.0 version compatible with React 18.

Could you update the npm package to include the latest version? This would help ensure compatibility and ease dependency management.

Thanks for the great library and looking forward to the update!

Best

**Comment by NishargShah** [comment]
Hello @DnAWebDev 

The current version `V1.5.1` supports react 18 and you can install `V2` by `npm install react-img-mapper@alpha`, no need to install it from Github.
